#ifndef __ENCODING_H__
#define __ENCODING_H__

typedef enum {
    OPCODE_SPECIAL      = 0x00,
    OPCODE_REGIMM       = 0x01,
    OPCODE_J            = 0x02,
    OPCODE_JAL          = 0x03,
    OPCODE_BEQ          = 0x04,
    OPCODE_BNE          = 0x05,
    OPCODE_BLEZ         = 0x06,
    OPCODE_BGTZ         = 0x07,
    OPCODE_ADDI         = 0x08,
    OPCODE_ADDIU        = 0x09,
    OPCODE_SLTI         = 0x0A,
    OPCODE_SLTIU        = 0x0B,
    OPCODE_ANDI         = 0X0C,
    OPCODE_ORI          = 0x0D,
    OPCODE_XORI         = 0x0E,
    OPCODE_AUI          = 0x0F,
    OPCODE_COP0         = 0x10,
    OPCODE_COP1         = 0x11,
    OPCODE_      = 0x12,
    OPCODE_      = 0x13,
    OPCODE_      = 0x14,
    OPCODE_      = 0x15,
    OPCODE_      = 0x16,
    OPCODE_      = 0x17,
    OPCODE_      = 0x18,
    OPCODE_      = 0x19,
    OPCODE_      = 0x1A,
    OPCODE_      = 0x1B,
    OPCODE_      = 0x1C,
    OPCODE_      = 0x1D,
    OPCODE_      = 0x1E,
    OPCODE_      = 0x1F,
    OPCODE_      = 0x,
    OPCODE_      = 0x,
    OPCODE_      = 0x,
    OPCODE_      = 0x,
    OPCODE_      = 0x,
    OPCODE_      = 0x,
    OPCODE_      = 0x,
    OPCODE_      = 0x,
    OPCODE_      = 0x,
} opcode_t;

#endif